name: demo_bloc
description: Learn Bloc pattern

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0
  http: ^0.12.0+1
  flutter_rating: ^0.0.2
  carousel_slider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - res/graphic/

  fonts:
  - family: Muli
    fonts:
    - asset: res/fonts/Muli-Bold.ttf
    - asset: res/fonts/Muli-SemiBold.ttf
    - asset: res/fonts/Muli-Regular.ttf

